version: '3'

services:
    nginx:
        image: victor1989bl/robo-test-frontend
        ports:
            - "80:80"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            
    backend: 
        image: victor1989bl/robo-test-backend
        depends_on:
            - mysql
            - redis
        volumes:
            - ./env/env.backend:/www/backend/.env

    mysql:
        image: mysql:8.0
        command: 
            - mysqld
            - --default-authentication-plugin=mysql_native_password
        volumes:
            - ./volumes/mysql:/var/lib/mysql
            - ./volumes/db-init.sql:/docker-entrypoint-initdb.d/setup.sql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: payment
            MYSQL_USER: payment

    redis:
        image: redis:latest